puk
PSUMaps/mini-app pull request #14
Opened 2024-05-06 13:48 UTC by li3pm

2024-05-06 14:53 UTC, esperor requested changes
1. .css файлы совершенно не нужны;
2. Используй tailwind;
3. IconType.tsx должен быть .ts;
4. Все истории должны быть .tsx;
5. Папки и файлы должны быть lower-case

Сделал rebase, тебе нужно выполнить `git pull -f`
Не надо рофлить с названиями коммитов, для них в readme есть инструкция. То же самое с названием веток в основном репе и PR.

2024-05-06 14:53 UTC, esperor commented on package.json
> +    "@mui/material": "^5.15.16",
Зачем этот dep? Он нигде не используется. Туда же и react-router-dom

2024-05-06 14:53 UTC, esperor commented on shared/assets/Icons/IconCalendar/IconCalendar.tsx
> +  const mode = isContrastIconCalendar ? "dark" : "light";
```suggestion
export const IconCalendar = ({ isContrast }: { isContrast?: boolean }) => {
  const mode = isContrast ? "dark" : "light";
```

`...IconCalendar` здесь лишнее; отдельная модель для одного prop'а - тоже

2024-05-06 14:53 UTC, esperor commented on shared/assets/Icons/IconCalendar/IconCalendar.tsx
> +      height="18"
```suggestion
      className="w-4 h-[1.15rem]"
```
1. Не следует использовать width и height, когда есть className (в которые проще вставлять параметры)
2. Не следует использовать px

2024-05-06 14:53 UTC, esperor commented on shared/assets/Icons/icon.css
css файл с двумя правилами - явно лишний css файл
Нужно убрать его, вместо него использовать 
```
className=`${isContrast ? 'stroke-c_main' : 'stroke-c_bg-block'}` 
```

Нельзя использовать hard-coded цвета (`#FEFEFE`), они уже прописаны в tailwind.config.ts (web/)

2024-05-06 14:53 UTC, esperor commented on shared/assets/Icons/IconFiltr/IconFiltr.tsx
Должно быть Filter, не Filtr

2024-05-06 14:53 UTC, esperor commented on shared/components/ButtonText/ButtonText.tsx
> +  url('https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,500;1,500&display=swap');
Шрифт уже определен в tailwind.config.ts и назначен для всех основных текстовых элементов (h1-5, p)

2024-05-06 14:53 UTC, esperor commented on shared/components/ButtonText/ButtonText.tsx
> +      className={[mode, `text-button--${typeButton}`, "text-button"].join(" ")}
Безобразие

2024-05-06 14:53 UTC, esperor commented on shared/components/Icon/Icon.tsx
Идея сделать один основной компонент Icon и таблицу со всеми иконками неплохая
Но зачем все иконки в формате react-компонентов вместо .svg файлов?

2024-05-06 14:53 UTC, esperor commented on shared/components/Icon/Icon.tsx
> +  return <div> {getIcon(type)}</div>;
Потеряла здесь mode, он не передается в иконку

2024-05-06 14:53 UTC, esperor commented on shared/stories/ButtonIcon.stories.ts
> +import { fn } from "@storybook/test";
Импорт нигде не используется

2024-05-06 14:53 UTC, esperor commented on shared/stories/ButtonIcon.stories.ts
> +    typeIcon: "Search",
Второй раз 'Search'

2024-05-06 14:53 UTC, esperor commented on shared/stories/ButtonIcon.stories.ts
> +  title: "Example/ButtonIcon",
```suggestion
  title: "Components/ButtonIcon",
```

2024-05-06 14:53 UTC, esperor commented on shared/stories/IconSearch.stories.ts
Зачем отдельный файл для IconSearch?

2024-05-06 14:57 UTC, esperor commented
Рекомендую использовать плагины из readme (prettier, tailwind IntelliSense)

2024-05-10 06:22 UTC, esperor commented on shared/components/ButtonText/ButtonText.tsx
> +  url('https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,500;1,500&display=swap');
Здесь ошибся, эта строка нужна
Добавил в index.css в dev ветке

2024-05-11 12:07 UTC, esperor requested changes

2024-05-11 12:07 UTC, esperor commented on package.json
> +    "react-router-dom": "^6.23.0",
где используется react-router-dom?

2024-05-15 13:22 UTC, esperor commented on shared/assets/Icons/icon.css
Проблема остается

2024-05-19 12:26 UTC, esperor approved these changes

2024-05-19 13:03 UTC, ijo42 approved these changes
в остальном нравится

2024-05-20 04:38 UTC, esperor commented on shared/components/common/button.tsx
> +      className={[
Исправлено

2024-05-20 04:43 UTC, merged