feat: event desc
PSUMaps/mini-app pull request #19
Opened 2024-05-20 13:38 UTC by Toderry

Closes #7 
**Добавляет окно  для отображения подробностей конкретного мероприятия**
Блок с продолжительностью мероприятия закомментирован, так как времени окончания нет в входных данных.
Время начала, дата и день недели преобразуются методами объекта Data.
Аватар организатора дефолтный всегда.

<details><summary>Скриншоты</summary>
<img width="336" alt="image" src="https://github.com/PSUMaps/mini-app/assets/106995468/25436c7c-56c2-4e06-8f8b-478e4caf8d21"> <img width="333" alt="image" src="https://github.com/PSUMaps/mini-app/assets/106995468/8d45a4a0-3df3-4d61-9898-6a103eba06af">
<img width="331" alt="image" src="https://github.com/PSUMaps/mini-app/assets/106995468/cafaeae0-5021-4d86-ac61-88234e222b3c">

</details>

2024-05-21 17:11 UTC, esperor commented
1. Визуально немножко сломаны иконки 
![image](https://github.com/PSUMaps/mini-app/assets/49198951/bdc1b54f-e472-431d-a1ee-9557e4bf28a4)
У меня тоже с календарем похожая ситуация была с иконкой календаря, могу попробовать помочь

2. svg аватарки в темной теме должна быть светлой
![image](https://github.com/PSUMaps/mini-app/assets/49198951/4a14928f-a652-4171-a9db-462d80e18ec4)

3. Padding потеряла
![image](https://github.com/PSUMaps/mini-app/assets/49198951/872e6f08-9725-489e-a8da-83cfd440c904)

4. Секунды лишние
![image](https://github.com/PSUMaps/mini-app/assets/49198951/d4a6894c-c47b-4ff6-a09e-4368f3375c51)

5. Неоднородный текст (+ непонятно, зачем используешь text-sm, font-medium и прочее, когда по макету сделаны классы специально: b1, b2 конкретно здесь)
![image](https://github.com/PSUMaps/mini-app/assets/49198951/047393a2-a153-4ce0-8c21-ea1ff8c95f4e)

6. Неоднородный паддинг карточки (сделай снизу как слева)
![image](https://github.com/PSUMaps/mini-app/assets/49198951/4ff78f78-89af-4acd-98cb-d3606ded0bf2)

7. В storybook сделай хотя бы один пример, чтобы layout был как на макете, то есть высокий и узкий, иначе сложно оценить

Пока код не смотрел, сначала это исправь
Но знаю, что код не идеальный, поэтому сразу говорю: используй существующие utilities и классы, особенно для текста

2024-05-28 13:20 UTC, esperor requested changes
Насколько я понял, все Card'ы относятся к eventCard и только в ней используются, а значит нужно создать отдельную папку (а еще перенести в timetable):
components / timetable /
-- eventCard /
-- -- index.tsx
-- -- contactsCard.tsx
...

2024-05-28 13:53 UTC, ijo42 commented on shared/components/common/heartButton.tsx
> +    const [person, setPerson] = useState(props.person)
active / setActive даже

2024-05-28 17:20 UTC, esperor commented on web/src/pages/event-description/index.tsx
Обновление: поменять название файла на eventDescription.tsx, файл положить в pages/timetable

2024-05-30 07:37 UTC, Toderry commented on web/tailwind.config.ts
> +        c_sub: '#444444',
1)
<img width="532" alt="image" src="https://github.com/PSUMaps/mini-app/assets/106995468/2a24825c-6721-4af4-b172-b5c8bd010936">
2) нет в макете

2024-06-04 17:22 UTC, esperor requested changes
В целом код хороший
Касательно структуры:
1. heartButton и shareButton вроде больше нигде не используются, зачем они в common?
2. в timetable сделать надо папку eventCard и в нее поместить все связанные файлы, а саму eventCard.tsx сделать index.tsx

2024-06-04 17:22 UTC, esperor commented on shared/components/timetable/eventCard.tsx
> +            }`}
Вынести в тело компонента и обернуть в useMemo
То же самое с датой начала выше

2024-06-04 17:22 UTC, esperor commented on shared/stories/eventCard.stories.tsx
> +export const Default2: Story = {
Поменять название на осмысленное (например LongTag)

2024-06-04 17:22 UTC, esperor commented on shared/components/common/shareButton.tsx
> +      className="h-10 w-10 rounded-full hover:scale-110"
Зачем в mobile-first сайте эффект на `hover`? Сделай на active и лучше тогда `active: scale-90`
То же самое с heartButton

2024-06-04 17:22 UTC, esperor commented on shared/components/timetable/eventCard.tsx
> +        <div className="flex relative flex-col w-full aspect-[2.13] ">
насколько оправдан `aspect-[2.13]`? 
на desktop он делает так: 
<details><summary>Скриншот</summary>

![image](https://github.com/PSUMaps/mini-app/assets/49198951/41dcf176-d790-42f9-9b65-c7437433f85a)

</details>

при этом на экране смартфона ничего не меняет

2024-06-05 09:41 UTC, Toderry commented on shared/components/timetable/eventCard.tsx
> +        <div className="flex relative flex-col w-full aspect-[2.13] ">
Картинки были разные по высоте, но сейчас нормально. Убрала

2024-06-05 18:00 UTC, esperor requested changes
Нужно убрать лишние расширения файлов из импортов; добавил в dev коммит с правилом лдя eslint, которое это контролирует
и замержил правило сюда

2024-06-05 18:06 UTC, esperor commented on shared/components/timetable/eventCard/index.tsx
> +              className="object-cover h-40 rounded-t-lg"
Попробуй сделать здесь aspect какой-нибудь и, возможно, ограничение по высоте (скажем, в vh), чтобы это выглядело хоть сколько-то одинаково на разных устройствах

2024-06-13 12:57 UTC, esperor requested changes
Looks good to me
Теперь нужно поработать над сетевой частью, а именно:
1. В компонент должен передаватсья только id, все остальные данные компонент запрашивает сам при помощи tanstack-query и httpClient,
2. В storybook запрос надо замокать

2024-06-13 12:57 UTC, esperor commented on shared/src/components/timetable/eventCard/heartButton.tsx
> +      className={`h-10 w-10 rounded-full active:scale-90 ${isActive ? 'bg-red-600 dark:bg-red-600' : ''}`}
Поменяй 'bg-red-600 dark:bg-red-600' на variant='accent' (сначала нужно merge dev)

2024-06-16 15:55 UTC, esperor requested changes
Отличаются border-radius у картинки и у карточки (на скриншоте), снизу кнопка зачем-то имеет цвет bg и не имеет нижний padding (скорее всего потому, что снизу должна быть еще информация - лучше сделать паддинг контенту карточки в целом, а не тому элементу, который должен быть нижним).
Кнопкам like и share не хватает свойств анимации (transition, duration, ease-in-out).

<details><summary>Скриншот</summary>

![image](https://github.com/PSUMaps/mini-app/assets/49198951/abf76c0e-e783-4010-8c31-7e3857e9f1dd)

</details>

2024-06-16 15:55 UTC, esperor commented on package.json
Зачем в корень добавлять tanstack?

2024-06-17 14:04 UTC, ijo42 commented on shared/src/components/timetable/eventCard/contactsCard.tsx
> +          <p className="c1">{organizer ?? 'Неизвестно'}</p>
ну уровне выше проверка парама убирает блок целиком, зачем ещё здесь?

2024-06-17 14:04 UTC, ijo42 commented on shared/src/components/timetable/eventCard/index.tsx
> +  const eventDate = useMemo(
eventDate используется лишь как элемент форматирования, отдельный useMemo не нужен

2024-06-17 14:04 UTC, ijo42 commented on shared/src/components/timetable/eventCard/shareButton.tsx
> +      link: `https://vk.com/app/${id}?`,
в константы

2024-06-17 14:14 UTC, esperor commented on shared/src/components/timetable/eventCard/shareButton.tsx
> +      link: `https://vk.com/app/${id}?`,
Исправил

2024-06-17 14:15 UTC, esperor commented on shared/src/components/timetable/eventCard/index.tsx
> +  const eventDate = useMemo(
Исправил

2024-06-17 14:15 UTC, esperor commented on shared/src/components/timetable/eventCard/contactsCard.tsx
> +          <p className="c1">{organizer ?? 'Неизвестно'}</p>
Исправил

2024-06-17 14:27 UTC, ijo42 approved these changes
lgtm

2024-06-17 14:28 UTC, merged