Feat modal
PSUMaps/mini-app pull request #20
Opened 2024-05-28 17:01 UTC by li3pm

2024-06-04 18:01 UTC, esperor requested changes
Для появления модала нужно добавить хотя бы простую анимацию - выезд снизу под ease-in-out
Сам модал надо перенести в shared, ему нечего делать в web, если только в нем не используются какие-то web-specific инструменты

2024-06-08 12:01 UTC, esperor requested changes
Качество кода объективно улучшила, практически привела к стандарту по проекту. Функционально же компонент не готов, API есть у CheckableText, но не у Modal в целом. Нужно сделать структурный объект по типу filtersData в истории, который будет передаваться в модал вместе с функцией его изменения (то есть будет `[filters, setFilters] = useState({...})`). Сам модал уже будет по событию от checkableText обновлять эту форму (фильтры). 
Сейчас проблема в том, что модал родителю не раскрывает _какой_ фильтр был включен или выключен, да и сам модал этого не знает, так как в onChange у checkableText идентификации не происходит.

Кроме того, надо поработать с названием и расположением компонента. Специализованный для фильтров событий модал надо положить в папку расписания событий - timetable, и назвать соответственно (название истории почти подходит, но следует поменять местами слова: modalEventFilters -> eventFiltersModal)

P.S. Заметил много "магических" значений в ремах, которые округляются только при переводе в пиксели. Не надо так делать, это тратит время и не приводит к значительному улучшению результата: на разных устройствах rem'ы будут выглядеть слегка по разному. Поэтому лучше использовать округления в пределах 5% (то есть 2.1rem ~ 2rem, 4.275 ~ 4.3 и так далее)

2024-06-13 12:39 UTC, esperor requested changes
Есть небольшие исправления, в целом хорошо. Остается интегрировать tanstack-query и замокать запросы

2024-06-13 12:39 UTC, esperor commented on shared/src/stories/eventFiltersModal.stories.tsx
> +      );
Нечитаемое выражение. Не стоит для этого использовать .map - он будет проходить по всем элементам
В данном случае можно заменить выражение полностью, но в будущем если будет сложное выражение, которое упростить нельзя, то его следует выделить в другую функцию
```suggestion
      setFilters((prevFilters) => {
        prevFilters
          .find((filter) => filter.id === filterId)!
          .values.find((value) => value.id === valueId)!.isChecked =
          event.target.checked;

        return [...prevFilters];
      });
```

2024-06-13 12:39 UTC, esperor commented on shared/src/stories/eventFiltersModal.stories.tsx
> +        </Button>
Обновил Button, теперь лучше так сделать

```suggestion
        <Button
          className={`h-10 w-10 rounded-forty`}
          variant={
            filters.some((filter) =>
              filter.values.some((value) => value.isChecked),
            )
              ? 'accent'
              : 'primary'
          }
          onClick={() => setModalActive(true)}
        >
          <FilterIcon />
        </Button>
```

2024-06-13 12:46 UTC, esperor commented on shared/components/modal/modal.tsx
> +          />
Проблема остается

2024-06-18 11:50 UTC, esperor approved these changes
LGTM

2024-06-18 12:02 UTC, ijo42 approved these changes
кроме рандомных id элементов все нравится

2024-06-18 12:09 UTC, esperor commented
> кроме рандомных id элементов все нравится

Исправил

2024-06-18 12:09 UTC, merged