Feat settings
PSUMaps/mini-app pull request #32
Opened 2024-06-08 14:11 UTC by Toderry

Closes #26 
**Окно настроек**
Внешний вид переключателя темы остался прежним

<details><summary>Скриншоты</summary>
<img width="262" alt="image" src="https://github.com/PSUMaps/mini-app/assets/106995468/96971fe3-688f-45ad-8196-ad0438af0c14">  
<img width="250" alt="image" src="https://github.com/PSUMaps/mini-app/assets/106995468/4c551269-fd20-41ac-b0d2-5781700a27a3">

2024-06-12 17:30 UTC, esperor requested changes
По коду практически нет замечаний, но структурно есть вопросы:
1. Зачем существует settingsCard, когда это по сути settingsPage? Уже есть settings/index.tsx, в котором должна собираться страница. Если идея в создании именно  shared компонента, то подход нужно слегка изменить - вернуть деление: на userCard и settings, в итоге страницу будем собирать из двух компонентов. 
2. Зачем история sb для цельной страницы (settingsCard)? Истории нужны для проверки работы компонента, целая страница в любом случае должна проверяться в билде/dev'е. Имеет смысл вернуть историю для userCard (хоть компонент и уменьшился, он все еще компонент) и убрать для settingsCard.

2024-06-13 11:38 UTC, esperor requested changes
Все красиво. Осталось замержить dev и интегрировать tanstack-query

2024-06-17 13:49 UTC, esperor approved these changes
LGTM

2024-06-17 13:56 UTC, ijo42 commented on shared/src/components/settings/index.tsx
> +        onClick={() => window.open('https://ya.ru/', '_blank')}
утащить в константы x3

2024-06-17 14:25 UTC, ijo42 approved these changes
lgtm

2024-06-17 14:30 UTC, merged