Feat timetable card
PSUMaps/mini-app pull request #39
Opened 2024-06-18 16:28 UTC by li3pm

2024-06-18 18:10 UTC, Toderry commented on shared/src/components/timetable/timetableCard/index.tsx
> +  const cardClassName = `${isClassInProgress ? 'bg-c_accent dark:bg-c_accent text-c_bg-block shadow-[0.06rem_0.06rem_0.3rem_0_#D01F3680] dark:shadow-[0.06rem_0.06rem_0.3rem_0_#D01F3680]' : 'bg-cd_mai
Зачем w-screen?

2024-06-18 18:19 UTC, Toderry commented on shared/src/components/timetable/timetableCard/index.tsx
> +      <div className="pt-[1.3rem] pb-[1.8rem] pl-[1.6rem] pr-[2.1rem] grid gap-4 grid-cols-2">
На длинном названии flex flex-row будет лучше смотреться, но тогда нужно gap больше сделать

2024-06-18 18:31 UTC, Toderry requested changes
:*

2024-06-19 04:10 UTC, esperor commented
Ветку надо пересоздать на основе текущего dev, пр, соответственно, тоже

2024-06-19 04:10 UTC, closed without merging