chore: update api
PSUMaps/mini-app pull request #48
Opened 2024-07-21 11:23 UTC by ijo42

- обновлен map api до версии 2
- обновлены стили карты

2024-07-21 11:32 UTC, esperor requested changes

2024-07-21 11:32 UTC, esperor commented on web/src/pages/map/index.tsx
> +  const style: StyleSpecification = useMemo(
Вынести бы куда-то

2024-07-21 11:32 UTC, esperor commented on web/src/pages/map/index.tsx
> +      sprite: 'https://tiles.ijo42.ru/assets/sprite/indoorequal',
url в коде?

2024-07-21 11:37 UTC, esperor requested changes

2024-07-21 11:37 UTC, esperor commented on web/src/pages/map/index.tsx
> +      String(Math.floor(e.features![0].id / 10)), // (ノ^_^)ノ┻━┻ ┬─┬
Комментарий объясняющий, пожалуйста

2024-07-21 13:19 UTC, ijo42 commented on web/src/pages/map/index.tsx
> +      String(Math.floor(e.features![0].id / 10)), // (ノ^_^)ノ┻━┻ ┬─┬
умом это не понять

2024-07-22 17:48 UTC, esperor reviewed
Было бы классно пофиксить...

2024-07-22 17:48 UTC, esperor commented on web/src/pages/map/index.tsx
> +      String(Math.floor(e.features![0].id / 10)), // в поле id приходит значение в 10 раз больше (ノ^_^)ノ┻━┻ ┬─┬
Typescript жалуется, что `e.features![0].id` может быть `undefined`. Надо или сделать fallback, или сделать `@ts-ignore` с объяснением

2024-07-22 17:48 UTC, esperor commented on web/src/mapEngine/layers.ts
> +  },
Typescript ругается

2024-07-25 13:26 UTC, esperor approved these changes
LGTM

2024-07-25 17:25 UTC, merged